<?php

namespace OC\projetBddBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * fichierRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class fichierRepository extends EntityRepository
{
}
