<?php

namespace OC\projetBddBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * motCleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class motCleRepository extends EntityRepository
{
}
